### ISSUE TITLE
Understanding the book and the code...

### ISSUE THREAD

**Issue by sipi41** [JonPSmith/EfCoreinAction-SecondEdition#13]
Hello, I was trying to contact the author or any who can help... is there any forum for questions about the book? I'm now at the section 2, and what I have is a full functional project, with all classes, several projects, services, repositories, etc etc... and the book only explains some parts of it... is there any part on the book that I actually create classes of the objects (book, author, etc)... how will I practice what is being shown? thank you for your help, maybe I'm missing something...

**Comment by sipi41** [comment]
In other words, the book ask me to open the project, run it and it runs, vuala! but how did we get to that point? when can I start building my own project? I did a blazor project, and linked the author's data project, but that means the dbcontext is already there, classes are there even the overrided method to create relatioships is already there... if I can't create my classes and the book only gives and idea of what the classes are, how will I memorize these things?

**Comment by JonPSmith** [comment]
Hi @sipi41,

My [Entity Framework Core in Action](https://bit.ly/EfCoreBookEd2) book is about Entity Framework Core (EF Core) and doesn't cover how to create applications. However I do provide example applications so that a) I am sure want I write in the book is correct, and b) users can try an application themself to see EF Core in action.

Of the apps in this repo the [Console App](https://github.com/JonPSmith/EfCoreinAction-SecondEdition/blob/master/MyFirstEfCoreApp/Program.cs) is the easiest app to understand, but the Part1 ASP.NET Core [BookApp](https://github.com/JonPSmith/EfCoreinAction-SecondEdition/tree/master/BookApp) is quite complex and the Part3 branch ASP.NET Core BookApp is VERY complex, due to performance features and Cosmos DB support.

I suggest you find articles / books about how to build the type of application you need. I would recommend the [ASP.NET Core in Action, Third Edition](https://www.manning.com/books/asp-net-core-in-action-third-edition) book, and the Microsoft documentation is also excellent.

**Comment by sipi41** [comment]
Thank you @JonPSmith sorry if I sound harsh, its because when you create something, most of the times you understand what you did there, and the reason to do it... when others see you code, they may not think the same way, I think we should start by creating our own classes, our own dbcontext and go from zero to develop the complete solution, and yes, you can provide a whole solution as a reference in case something goes bad on the way... we are not (or at least me) as smart as you, just a suggestion.
