### ISSUE TITLE
Changing provider

### ISSUE THREAD

**Issue by KevinBurton** [JonPSmith/EfCoreinAction-SecondEdition#4]
I would like to change the provider to one for MariaDB. How is this done?

**Comment by BenHayat** [comment]
> 
> 
> I would like to change the provider to one for MariaDB. How is this done?

Kevin, firstly be sure MariaDB or other providers support .Net 5 (in case you're using EF5). Previously MySQL or other derivatives were way behind supporting .Net current version.

Secondly, the providers generally provide docs how to use their provider in startup.cs. I use PostgreSQL and they provide all the info what library to use and etc.

**Comment by JonPSmith** [comment]
Hi @KevinBurton,

My book and this repo uses SQL Server because its installed when Visual Studio is installed - that makes it easier for beginners. But as @BenHayat said EF Core is the generally same for all database providers. I do look at some of the differences in section 16.8 of my book.

PS. I assume you know that `Pomelo.EntityFrameworkCore.MySql` says its supports MariaDB. I haven't used it so I can't say how good it is.
