### ISSUE TITLE
Get exception when trying to run 'MyFirstEfCoreApp' the second time

### ISSUE THREAD

**Issue by rmckay49** [JonPSmith/EfCoreinAction-SecondEdition#8]
I cloned the part 1 project and ran the 'MyFirstEfCoreApp' project.  It created the database and created the console window.  All of the switch options worked.  I wanted to walk through the code so I deleted the database 'MyFirstEfCoreDb' found in "C:\Users\Owner".  When I rerun the 'MyFirstEfCoreApp' project I get an exception from
` db.Database.EnsureCreated();`
` Message=Database 'MyFirstEfCoreDb' already exists. Choose a different database name.
  Source=Core Microsoft SqlClient Data Provider`
I've tried several Stack Overflow suggestions to delete the database.  None have worked and I've cannot find the database.  What am I missing?

**Comment by JonPSmith** [comment]
Hi @rmckay49,

You can't just delete the database, because SQL Server will still have that database registered with the database server called `localdb`. To delete a database you need to delete the database via some form of SQL Server management tools - the best known is [SQL Server Management Studio](https://docs.microsoft.com/en-us/sql/ssms/sql-server-management-studio-ssms), which is free.

At this point you have deleted the database, so you need to [detach the database](https://docs.microsoft.com/en-us/sql/relational-databases/databases/detach-a-database?view=sql-server-ver15#SSMSProcedure)  because a delete via SSMS will fail.

I trust that helps you.

**Comment by rmckay49** [comment]
That did it.  Thanks Jon.
